remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  # <-- blog.md
    - name: Whatever  # <-- whatever.md
    
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: crf3@hw.ac.uk
      link: mailto:crf3@hw.ac.uk
  follow:
    - name: Twitter
      link: https://twitter.com/clary_fary_
      username: "@clary_fary_"
    - name: YouTube
      link: https://www.youtube.com/channel/UCWGzrezCGIKW_cfchwxIMEQ
      

