remote_theme: claryflegel/bay
title: Clara Flegel

header: 
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Projects  # <-- blog.md
    
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: crf3@hw.ac.uk
      link: mailto:crf3@hw.ac.uk
  follow:
    - name: Twitter
      link: https://twitter.com/clary_fary_
      username: "@clary_fary_"
      

