remote_theme: claryflegel/bay
title: Clara Flegel

header: 
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Projects  # <-- blog.md
    - name: Reading # <-- reading.md
    
footer:
  show_powered_by: false
  follow:
    - name: Twitter
      link: https://twitter.com/clary_fary_
      username: "@clary_fary_"
      

